/**
 * Reference test vectors generated by running the actual decompiled Android
 * encoding logic (WopReferenceEncoder.java). Each vector contains the exact
 * frame and bitstream output from the Java code for a given set of inputs.
 *
 * These tests verify that the TypeScript encoder produces bit-identical output
 * to the original Android app.
 */
import {
  encodeTimezone,
  encodeTime,
  encodeDate,
  assembleFrame,
  buildBitstream,
  type TransmitParams,
} from '../encoder';

// Reference vectors from Java (WopReferenceEncoder.java)
interface DstEventRef {
  season: number;
  month: number;
  day: number;
  hour: number;
}

interface ReferenceVector {
  name: string;
  isT1: boolean;
  tzShift: number;
  minuteShiftOrd: number;
  hemisphereOrd: number;
  hour: number;
  minute: number;
  second: number;
  year: number;
  month: number;
  day: number;
  dstSummer: DstEventRef | null;
  dstWinter: DstEventRef | null;
  headerBits: number[];
  tzBits: number[];
  timeBits: number[];
  dateBits: number[];
  frame: number[];
  bitstream: number[];
}

const VECTORS: ReferenceVector[] = [
  {
    "name": "UTC+0 London no DST",
    "isT1": true,
    "tzShift": 0,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 12, "minute": 0, "second": 0,
    "year": 26, "month": 3, "day": 8,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,0,0,0,0,0,0],
    "timeBits": [0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0]
  },
  {
    "name": "UTC+1 Berlin standard T2",
    "isT1": false,
    "tzShift": 1,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 9, "minute": 57, "second": 25,
    "year": 26, "month": 1, "day": 15,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,0,0,1,0,0,0],
    "timeBits": [0,1,0,0,1,1,1,1,0,0,1,0,1,1,0,0,1],
    "dateBits": [0,0,1,1,0,1,0,0,0,0,1,0,1,1,1,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,1,0,0,1,0,1,1,0,0,1,0,0,1,1,0,1,0,0,0,0,1,0,1,1,1,1,0,0,0,1,0,0,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,1,1,0,0,1,0,1,1,0,0,1,0,0,1,1,0,1,0,0,0,0,1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0]
  },
  {
    "name": "UTC+2 Berlin DST active T1",
    "isT1": true,
    "tzShift": 2,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 14, "minute": 30, "second": 45,
    "year": 26, "month": 7, "day": 20,
    "dstSummer": { "season": 0, "month": 3, "day": 29, "hour": 2 },
    "dstWinter": { "season": 1, "month": 10, "day": 25, "hour": 3 },
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,0,1,0,0,0,0],
    "timeBits": [0,1,1,1,0,0,1,1,1,1,0,1,0,1,1,0,1],
    "dateBits": [0,0,1,1,0,1,0,0,1,1,1,1,0,1,0,0],
    "frame": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,1,1,0,0,1,1,1,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1,1,0,1,0,0,0,1,0,1,1,0,1,0,1,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,1,1,1,0,0,1,1,1,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1,1,0,0,1,0,0,0,1,0,1,1,0,1,0,1,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0]
  },
  {
    "name": "UTC-8 LA no DST",
    "isT1": true,
    "tzShift": -8,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 3, "minute": 15, "second": 30,
    "year": 26, "month": 12, "day": 25,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [1,1,0,0,0,0,0,0],
    "timeBits": [0,0,0,1,1,0,0,1,1,1,1,0,1,1,1,1,0],
    "dateBits": [0,0,1,1,0,1,0,1,1,0,0,1,1,0,0,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,1,1,0,1,1,1,1,0,0,0,1,1,0,1,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,1,1,0,1,1,1,1,0,0,0,1,1,0,1,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,0,0,0]
  },
  {
    "name": "UTC-4 NYC DST active T1",
    "isT1": true,
    "tzShift": -4,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 18, "minute": 45, "second": 0,
    "year": 26, "month": 6, "day": 15,
    "dstSummer": { "season": 0, "month": 3, "day": 8, "hour": 2 },
    "dstWinter": { "season": 1, "month": 11, "day": 1, "hour": 2 },
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [1,1,1,0,0,0,0,0],
    "timeBits": [1,0,0,1,0,1,0,1,1,0,1,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,1,1,0,0,1,1,1,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,0,1,0,0,1,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,1,0,0,1,1,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,0,1,1,0,0,1,0,1,0,1,1,0,1,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,1,1,0,0,1,1,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0,0,0]
  },
  {
    "name": "UTC+5:30 India no DST",
    "isT1": true,
    "tzShift": 5,
    "minuteShiftOrd": 1,
    "hemisphereOrd": 0,
    "hour": 8, "minute": 0, "second": 0,
    "year": 26, "month": 3, "day": 8,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,1,0,1,0,1,0],
    "timeBits": [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1,1,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1,1,0,0,0]
  },
  {
    "name": "UTC+5:45 Nepal no DST",
    "isT1": true,
    "tzShift": 5,
    "minuteShiftOrd": 2,
    "hemisphereOrd": 0,
    "hour": 8, "minute": 0, "second": 0,
    "year": 26, "month": 3, "day": 8,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,1,0,1,1,0,0],
    "timeBits": [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,1,0,1,1,0,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,1,0,1,1,0,0,0,0,0]
  },
  {
    "name": "UTC+11 Sydney DST active T1",
    "isT1": true,
    "tzShift": 11,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 1,
    "hour": 0, "minute": 0, "second": 0,
    "year": 26, "month": 1, "day": 1,
    "dstSummer": { "season": 0, "month": 10, "day": 4, "hour": 2 },
    "dstWinter": { "season": 1, "month": 4, "day": 5, "hour": 3 },
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,1,0,1,1,0,0,1],
    "timeBits": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,1,1,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,0,1,1,0,1,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0,1,0,1,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,1,1,0,1,0,1,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,0,1,1,0,1,0,0,0]
  },
  {
    "name": "UTC+0 max time/date",
    "isT1": true,
    "tzShift": 0,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 23, "minute": 59, "second": 59,
    "year": 99, "month": 12, "day": 31,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,0,0,0,0,0,0,0],
    "timeBits": [1,0,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1],
    "dateBits": [1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,1,0,1,1,1,1,1,1,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,1,0,0,0]
  },
  {
    "name": "UTC-12 extreme negative",
    "isT1": true,
    "tzShift": -12,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 0, "minute": 0, "second": 0,
    "year": 26, "month": 6, "day": 1,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [1,0,1,0,0,0,0,0],
    "timeBits": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "dateBits": [0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,1,0,1],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,1,0,0,1,1,1,1,0,1,0,0]
  },
  {
    "name": "UTC+15 extreme positive",
    "isT1": true,
    "tzShift": 15,
    "minuteShiftOrd": 0,
    "hemisphereOrd": 0,
    "hour": 12, "minute": 30, "second": 30,
    "year": 26, "month": 6, "day": 1,
    "dstSummer": null,
    "dstWinter": null,
    "headerBits": [1,1,1,0,1,0,1,0],
    "tzBits": [0,1,1,1,1,0,0,0],
    "timeBits": [0,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,0],
    "dateBits": [0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1],
    "frame": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,1,1,1,1,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,0],
    "bitstream": [1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,1,1,1,1,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,0]
  },
];

// =============================================================================
// Individual field tests
// =============================================================================

describe('Java reference: individual field encoding', () => {
  for (const v of VECTORS) {
    test(`${v.name}: timezone bits`, () => {
      const actual = encodeTimezone(v.tzShift, v.minuteShiftOrd, v.hemisphereOrd);
      expect(actual).toEqual(v.tzBits);
    });

    test(`${v.name}: time bits`, () => {
      const actual = encodeTime(v.hour, v.minute, v.second);
      expect(actual).toEqual(v.timeBits);
    });

    test(`${v.name}: date bits`, () => {
      const actual = encodeDate(v.year, v.month, v.day);
      expect(actual).toEqual(v.dateBits);
    });
  }
});

// =============================================================================
// Frame assembly tests (pre-stuffing)
// =============================================================================

describe('Java reference: frame assembly', () => {
  for (const v of VECTORS) {
    test(`${v.name}: assembleFrame matches Java`, () => {
      const utc = new Date(Date.UTC(2000 + v.year, v.month - 1, v.day, v.hour, v.minute, v.second));
      const params: TransmitParams = {
        targetTimezone: v.isT1 ? 'T1' : 'T2',
        utcTime: utc,
        tz: {
          shiftHours: v.tzShift,
          minuteShift: v.minuteShiftOrd,
          hemisphere: v.hemisphereOrd,
          dstActive: false, // shift is already adjusted in test vectors
        },
        dstSummer: v.dstSummer ?? undefined,
        dstWinter: v.dstWinter ?? undefined,
      };
      const actual = assembleFrame(params);
      expect(actual).toEqual(v.frame);
    });
  }
});

// =============================================================================
// Full bitstream tests (with stuffing + trailing zeros)
// =============================================================================

describe('Java reference: full bitstream', () => {
  for (const v of VECTORS) {
    test(`${v.name}: buildBitstream matches Java`, () => {
      const utc = new Date(Date.UTC(2000 + v.year, v.month - 1, v.day, v.hour, v.minute, v.second));
      const params: TransmitParams = {
        targetTimezone: v.isT1 ? 'T1' : 'T2',
        utcTime: utc,
        tz: {
          shiftHours: v.tzShift,
          minuteShift: v.minuteShiftOrd,
          hemisphere: v.hemisphereOrd,
          dstActive: false,
        },
        dstSummer: v.dstSummer ?? undefined,
        dstWinter: v.dstWinter ?? undefined,
      };
      const actual = buildBitstream(params);
      expect(actual).toEqual(v.bitstream);
    });
  }
});
